### for문
* 반복 실행문
* for 변수 in 반복실행사용데이터:
* ....실행문1
* ....실행문2
* 실행문4
* 반복실행에 사용할 데이터를 list, range, dictionary.keys() 형태로 제공
* 해당 데이터를 하나씩 사용하여 모두 소진할때까지 반복 실행

In [1]:
# i 는 반복실행을 제어하는 변수
# range(0, 10) : 반복횟수를 정해주는 범위내 숫자 발생 함수
# 반복 실행의 시작 명령부터 끝 명령까지를 들여쓰기를 통해 표시해줍니다.
for i in range(0, 10):
    print("겁나 쉬운 파이썬 프로그래밍")

겁나 쉬운 파이썬 프로그래밍
겁나 쉬운 파이썬 프로그래밍
겁나 쉬운 파이썬 프로그래밍
겁나 쉬운 파이썬 프로그래밍
겁나 쉬운 파이썬 프로그래밍
겁나 쉬운 파이썬 프로그래밍
겁나 쉬운 파이썬 프로그래밍
겁나 쉬운 파이썬 프로그래밍
겁나 쉬운 파이썬 프로그래밍
겁나 쉬운 파이썬 프로그래밍

In [4]:
# range(시작숫자, 끝숫자+1)
# 시작 숫자 부터 끝숫자까지의 정수를 발생해 주는 함수입니다
# 발생된 숫자들은 차례로 i변수에 저장되면서 반복실행이 진행됩니다.
# 아래 예제는 1부터 9까지 정수를 발행하고 그 갯수 만큼 반복실행하는 예
# i 변수가 반복 실행마다 저장하는 값을 출력해봅니다
for i in range(1, 10):
    print(i, end=" ")
# print 명령에 줄바끔 기능을 없애려면  end="" 또는 end=" " 를 씁니다

1 2 3 4 5 6 7 8 9

In [6]:
# 10번의 반복을 위해서 반드시 range(0, 10) 이 필요한것은 아닙니다
for i in range(10, 20):
    print(i, end=" ")
print()
for i in range(100, 110):
    print(i, end=" ")

10 11 12 13 14 15 16 17 18 19
100 101 102 103 104 105 106 107 108 109

In [7]:
# range 함수는 리스트의 슬라이싱처럼 증감량이 존재하여 그 크기를 조절할수
# 있습니다
for i in range(10, 0, -1):
    print(i, end=" ")

10 9 8 7 6 5 4 3 2 1

In [10]:
# range 를 이용한 다양한 반복실행의 예
# 0 부터 99까지의 정수 출력
for i in range(0,100):
    print(i, end=" ")
print("\n")
# 1부터 100 사이의 짝수 출력 1
for i in range(2, 100, 2):
    print(i, end=" ")

0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99

2 4 6 8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94 96 98

In [11]:
# 1 부터 10 까지  합 계산
sum = 0
j = 0
for i in range(1, 11):
    j = j + 1
    sum = sum + j
print("합계 : ", sum)

합계 :  55

In [12]:
sum = 0
for i in range(1, 11):
    sum = sum + i
print("합계 : ", sum)

합계 :  55

In [16]:
sum = 0
for i in range(1, 1001):
    sum = sum + i
    print(sum, end=" ")

1 3 6 10 15 21 28 36 45 55 66 78 91 105 120 136 153 171 190 210 231 253 276 300 325 351 378 406 435 465 496 528 561 595 630 666 703 741 780 820 861 903 946 990 1035 1081 1128 1176 1225 1275 1326 1378 1431 1485 1540 1596 1653 1711 1770 1830 1891 1953 2016 2080 2145 2211 2278 2346 2415 2485 2556 2628 2701 2775 2850 2926 3003 3081 3160 3240 3321 3403 3486 3570 3655 3741 3828 3916 4005 4095 4186 4278 4371 4465 4560 4656 4753 4851 4950 5050 5151 5253 5356 5460 5565 5671 5778 5886 5995 6105 6216 6328 6441 6555 6670 6786 6903 7021 7140 7260 7381 7503 7626 7750 7875 8001 8128 8256 8385 8515 8646 8778 8911 9045 9180 9316 9453 9591 9730 9870 10011 10153 10296 10440 10585 10731 10878 11026 11175 11325 11476 11628 11781 11935 12090 12246 12403 12561 12720 12880 13041 13203 13366 13530 13695 13861 14028 14196 14365 14535 14706 14878 15051 15225 15400 15576 15753 15931 16110 16290 16471 16653 16836 17020 17205 17391 17578 17766 17955 18145 18336 18528 18721 18915 19110 19306 19503 19701 19900 20100 20301 20503 20706 20910 21115 21321 21528 21736 21945 22155 22366 22578 22791 23005 23220 23436 23653 23871 24090 24310 24531 24753 24976 25200 25425 25651 25878 26106 26335 26565 26796 27028 27261 27495 27730 27966 28203 28441 28680 28920 29161 29403 29646 29890 30135 30381 30628 30876 31125 31375 31626 31878 32131 32385 32640 32896 33153 33411 33670 33930 34191 34453 34716 34980 35245 35511 35778 36046 36315 36585 36856 37128 37401 37675 37950 38226 38503 38781 39060 39340 39621 39903 40186 40470 40755 41041 41328 41616 41905 42195 42486 42778 43071 43365 43660 43956 44253 44551 44850 45150 45451 45753 46056 46360 46665 46971 47278 47586 47895 48205 48516 48828 49141 49455 49770 50086 50403 50721 51040 51360 51681 52003 52326 52650 52975 53301 53628 53956 54285 54615 54946 55278 55611 55945 56280 56616 56953 57291 57630 57970 58311 58653 58996 59340 59685 60031 60378 60726 61075 61425 61776 62128 62481 62835 63190 63546 63903 64261 64620 64980 65341 65703 66066 66430 66795 67161 67528 67896 68265 68635 69006 69378 69751 70125 70500 70876 71253 71631 72010 72390 72771 73153 73536 73920 74305 74691 75078 75466 75855 76245 76636 77028 77421 77815 78210 78606 79003 79401 79800 80200 80601 81003 81406 81810 82215 82621 83028 83436 83845 84255 84666 85078 85491 85905 86320 86736 87153 87571 87990 88410 88831 89253 89676 90100 90525 90951 91378 91806 92235 92665 93096 93528 93961 94395 94830 95266 95703 96141 96580 97020 97461 97903 98346 98790 99235 99681 100128 100576 101025 101475 101926 102378 102831 103285 103740 104196 104653 105111 105570 106030 106491 106953 107416 107880 108345 108811 109278 109746 110215 110685 111156 111628 112101 112575 113050 113526 114003 114481 114960 115440 115921 116403 116886 117370 117855 118341 118828 119316 119805 120295 120786 121278 121771 122265 122760 123256 123753 124251 124750 125250 125751 126253 126756 127260 127765 128271 128778 129286 129795 130305 130816 131328 131841 132355 132870 133386 133903 134421 134940 135460 135981 136503 137026 137550 138075 138601 139128 139656 140185 140715 141246 141778 142311 142845 143380 143916 144453 144991 145530 146070 146611 147153 147696 148240 148785 149331 149878 150426 150975 151525 152076 152628 153181 153735 154290 154846 155403 155961 156520 157080 157641 158203 158766 159330 159895 160461 161028 161596 162165 162735 163306 163878 164451 165025 165600 166176 166753 167331 167910 168490 169071 169653 170236 170820 171405 171991 172578 173166 173755 174345 174936 175528 176121 176715 177310 177906 178503 179101 179700 180300 180901 181503 182106 182710 183315 183921 184528 185136 185745 186355 186966 187578 188191 188805 189420 190036 190653 191271 191890 192510 193131 193753 194376 195000 195625 196251 196878 197506 198135 198765 199396 200028 200661 201295 201930 202566 203203 203841 204480 205120 205761 206403 207046 207690 208335 208981 209628 210276 210925 211575 212226 212878 213531 214185 214840 215496 216153 216811 217470 218130 218791 219453 220116 220780 221445 222111 222778 223446 224115 224785 225456 226128 226801 227475 228150 228826 229503 230181 230860 231540 232221 232903 233586 234270 234955 235641 236328 237016 237705 238395 239086 239778 240471 241165 241860 242556 243253 243951 244650 245350 246051 246753 247456 248160 248865 249571 250278 250986 251695 252405 253116 253828 254541 255255 255970 256686 257403 258121 258840 259560 260281 261003 261726 262450 263175 263901 264628 265356 266085 266815 267546 268278 269011 269745 270480 271216 271953 272691 273430 274170 274911 275653 276396 277140 277885 278631 279378 280126 280875 281625 282376 283128 283881 284635 285390 286146 286903 287661 288420 289180 289941 290703 291466 292230 292995 293761 294528 295296 296065 296835 297606 298378 299151 299925 300700 301476 302253 303031 303810 304590 305371 306153 306936 307720 308505 309291 310078 310866 311655 312445 313236 314028 314821 315615 316410 317206 318003 318801 319600 320400 321201 322003 322806 323610 324415 325221 326028 326836 327645 328455 329266 330078 330891 331705 332520 333336 334153 334971 335790 336610 337431 338253 339076 339900 340725 341551 342378 343206 344035 344865 345696 346528 347361 348195 349030 349866 350703 351541 352380 353220 354061 354903 355746 356590 357435 358281 359128 359976 360825 361675 362526 363378 364231 365085 365940 366796 367653 368511 369370 370230 371091 371953 372816 373680 374545 375411 376278 377146 378015 378885 379756 380628 381501 382375 383250 384126 385003 385881 386760 387640 388521 389403 390286 391170 392055 392941 393828 394716 395605 396495 397386 398278 399171 400065 400960 401856 402753 403651 404550 405450 406351 407253 408156 409060 409965 410871 411778 412686 413595 414505 415416 416328 417241 418155 419070 419986 420903 421821 422740 423660 424581 425503 426426 427350 428275 429201 430128 431056 431985 432915 433846 434778 435711 436645 437580 438516 439453 440391 441330 442270 443211 444153 445096 446040 446985 447931 448878 449826 450775 451725 452676 453628 454581 455535 456490 457446 458403 459361 460320 461280 462241 463203 464166 465130 466095 467061 468028 468996 469965 470935 471906 472878 473851 474825 475800 476776 477753 478731 479710 480690 481671 482653 483636 484620 485605 486591 487578 488566 489555 490545 491536 492528 493521 494515 495510 496506 497503 498501 499500 500500

#### 연습 문제 1
* 정수를 입력 받아서, 입력 받은 정수에 해당하는 구구단을 출력하세요
* 정수 입력 : 5
* 5x1=5
* 5x2=10
* 5x3=15
* ...
* 5x9=45

In [17]:
a = int( input("출력할 구구단의 단 입력 :") )
for i in range(1, 10):
    print(a,"x",i,"=", a*i)

출력할 구구단의 단 입력 :8
8 x 1 = 8
8 x 2 = 16
8 x 3 = 24
8 x 4 = 32
8 x 5 = 40
8 x 6 = 48
8 x 7 = 56
8 x 8 = 64
8 x 9 = 72

#### 연습문제2
* 정수를 입력 받고, 입력 받은 정수의 factorial 을 계산하여 출력하세요
* (입력)정수입력 : 6
* (출력)6! = 1x2x3x4x5x6 = 720

In [19]:
n = int( input("정수 입력 : ") )
fact = 1
print( n, "! = ", end = "")
for i in range(1, n+1):
    print(i, "x", end=" ")
    fact = fact * i
print("\b\b = ", fact)

정수 입력 : 6
6 ! = 1 x 2 x 3 x 4 x 5 x 6  =  720

In [20]:
n = int( input("정수 입력 : ") )
fact = 1
print( n, "! = ", end = "")
for i in range(1, n):
    print(i, "x", end=" ")
    fact = fact * i
print(n, " = ", fact*n)

정수 입력 : 6
6 ! = 1 x 2 x 3 x 4 x 5 x 6  =  720

* (출력)6! = 6x5x4x3x2x1 = 720

In [21]:
n = int( input("정수 입력 : ") )
fact = 1
print( n, "! = ", end = "")
for i in range(n, 1, -1):   # 6부터 2까지
    print(i, "x", end=" ")
    fact = fact * i
print(1, " = ", fact*1)

정수 입력 : 6
6 ! = 6 x 5 x 4 x 3 x 2 x 1  =  720

#### 연습문제3
* 년, 월, 일을 입력 받아서 요일을 출력하세요
* 년도에 해당하는 계산은 입력한 년도의 전년도에 365를 곱하고,
* 1부터 전년도까지 윤년인지를 모두 검사해서 윤년이 나오면 1증가하는 반복문을 사용하세요

In [1]:
year = int( input("년도 입력:"))
month = int( input("월 입력 : ") )
day = int( input("일 입력 : ") )

# 입력한 년도의 전년도까지 날짜수를 365 를 곱해서 계산
total = 365 * (year-1)

# 입력한 년도의 전년도까지 윤년이 몇번있었는지 검사해서 1씩 덧샘합니다
for i in range(1, year):
    if (i%4==0) and (i%100!=0) or (i%400==0):
        total = total + 1
        
# 입력한년도 윤년인지 검사한 후 feb 변수에 28 또는 29  를 저장한 후
# 2월의 날짜수로 활용합니다
if (year%4==0) and (year%100!=0) or (year%400==0):
    feb = 29
else:
    feb = 28

# 위 상황에 맞게 아래 if 문을 수정합니다.
if month==1: total = total
elif month==2: total = total + 31
elif month==3: total = total + 31+feb
elif month==4: total = total + 31+feb+31
elif month==5: total = total + 31+feb+31+30
elif month==6: total = total + 31+feb+31+30+31
elif month==7: total = total + 31+feb+31+30+31+30
elif month==8: total = total + 31+feb+31+30+31+30+31
elif month==9: total = total + 31+feb+31+30+31+30+31+31
elif month==10: total = total + 31+feb+31+30+31+30+31+31+30
elif month==11: total = total + 31+feb+31+30+31+30+31+31+30+31
elif month==12: total = total + 31+feb+31+30+31+30+31+31+30+31+30
# 조건에 걸린 명령이 한개만 있다면 위와 같이 if 또는 elif 와 나란히 표기가
# 가능합니다
total = total + day
n = total % 7
if n==1: print("월요일입니다")
elif n==2: print("화요일입니다")
elif n==3: print("수요일입니다")
elif n==4: print("목요일입니다")
elif n==5: print("금요일입니다")
elif n==6: print("토요일입니다")
elif n==0: print("일요일입니다")

년도 입력:2021
월 입력 : 2
일 입력 : 16
화요일입니다

In [2]:
# 리스트의 요소들을 반복 실행문으로 접근 1
a = ['one', 'two', 'three', 'four']
for i in range(0, 4):
    print( a[i], end="  ")

one  two  three  four

In [3]:
# 리스트의 요소들을 반복 실행문으로 접근 2
a = ['one', 'two', 'three', 'four']
for i in a:
    print( i, end="  ")
# 반복실행의 데이터로 리스트를 제공하였습니다.
# 리스트의 요소들이 i 변수에 하나씩 차례로 저장되면서 반복실행이 진행됩니다

one  two  three  four

In [5]:
year = int( input("년도 입력:"))
month = int( input("월 입력 : ") )
day = int( input("일 입력 : ") )
total = 365 * (year-1)
for i in range(1, year):
    if (i%4==0) and (i%100!=0) or (i%400==0):
        total = total + 1
mdays = [0, 31, 28, 31 ,30 ,31 ,30 ,31 ,31 ,30, 31 ,30 ,31]
if (year%4==0) and (year%100!=0) or (year%400==0):
    mdays[2] = 29
for i in range(1, month):
    total = total + mdays[i]
total = total + day
n = total % 7
if n==1: print("월요일입니다")
elif n==2: print("화요일입니다")
elif n==3: print("수요일입니다")
elif n==4: print("목요일입니다")
elif n==5: print("금요일입니다")
elif n==6: print("토요일입니다")
elif n==0: print("일요일입니다")

년도 입력:2021
월 입력 : 2
일 입력 : 16
화요일입니다

In [6]:
#이중 반복문
for i in range(0,10):
    for j in range(0, 10):
        print("#", end="")
    print()

##########
##########
##########
##########
##########
##########
##########
##########
##########
##########

In [9]:
for i in range(1,10):
    for j in range(2, 10):
        print("%dx%d=%2d" % (j, i, i*j), end="  ")
    print()

2x1= 2  3x1= 3  4x1= 4  5x1= 5  6x1= 6  7x1= 7  8x1= 8  9x1= 9
2x2= 4  3x2= 6  4x2= 8  5x2=10  6x2=12  7x2=14  8x2=16  9x2=18
2x3= 6  3x3= 9  4x3=12  5x3=15  6x3=18  7x3=21  8x3=24  9x3=27
2x4= 8  3x4=12  4x4=16  5x4=20  6x4=24  7x4=28  8x4=32  9x4=36
2x5=10  3x5=15  4x5=20  5x5=25  6x5=30  7x5=35  8x5=40  9x5=45
2x6=12  3x6=18  4x6=24  5x6=30  6x6=36  7x6=42  8x6=48  9x6=54
2x7=14  3x7=21  4x7=28  5x7=35  6x7=42  7x7=49  8x7=56  9x7=63
2x8=16  3x8=24  4x8=32  5x8=40  6x8=48  7x8=56  8x8=64  9x8=72
2x9=18  3x9=27  4x9=36  5x9=45  6x9=54  7x9=63  8x9=72  9x9=81

In [10]:
for i in range(1,10):
    for j in range(2, 6):
        print("%dx%d=%2d" % (j, i, i*j), end="  ")
    print()
print()    
for i in range(1,10):
    for j in range(6, 10):
        print("%dx%d=%2d" % (j, i, i*j), end="  ")
    print()

2x1= 2  3x1= 3  4x1= 4  5x1= 5
2x2= 4  3x2= 6  4x2= 8  5x2=10
2x3= 6  3x3= 9  4x3=12  5x3=15
2x4= 8  3x4=12  4x4=16  5x4=20
2x5=10  3x5=15  4x5=20  5x5=25
2x6=12  3x6=18  4x6=24  5x6=30
2x7=14  3x7=21  4x7=28  5x7=35
2x8=16  3x8=24  4x8=32  5x8=40
2x9=18  3x9=27  4x9=36  5x9=45

6x1= 6  7x1= 7  8x1= 8  9x1= 9
6x2=12  7x2=14  8x2=16  9x2=18
6x3=18  7x3=21  8x3=24  9x3=27
6x4=24  7x4=28  8x4=32  9x4=36
6x5=30  7x5=35  8x5=40  9x5=45
6x6=36  7x6=42  8x6=48  9x6=54
6x7=42  7x7=49  8x7=56  9x7=63
6x8=48  7x8=56  8x8=64  9x8=72
6x9=54  7x9=63  8x9=72  9x9=81

#### 정수를 입력받아서 소수인지 아닌지를 출력하세요
* 소수(prime number)를 판단하는 방법
    * n 에 저장된 값이 소수인지 아닌지 판단하려면, 1부터 n 까지의 모든 숫자로 n 을 나눕니다
    * 나눈 나머지가 0인 경우가 몇번이었는지 count 하고 count 값이 2이면 소수로 출력합니다
    * count가 2라는건 1과 자기자신(n) 으로 나눴을때만 나머지가 0이었다는 뜻

In [12]:
n = int(input("정수 입력 : "))
count = 0
for i in range(1, n+1):
    if n % i == 0 :
        count = count+1
if count==2:
    print("소수입니다")
else :
    print("소수가 아닙니다")

정수 입력 : 89
소수입니다

#### 1부터 100 사이에 있는 모든 소수 출력

In [14]:
for n in range(2, 101):
    count = 0
    for i in range(2, n):
        if n % i == 0 :
            count = count+1
    if count==0:
        print(n, end=" ")

2 3 5 7 11 13 17 19 23 29 31 37 41 43 47 53 59 61 67 71 73 79 83 89 97

#### 년도와 월을 입력받고 해당 달력을 출력하세요

In [20]:
year = int( input("년도 입력:"))
month = int( input("월 입력 : ") )
total = 365 * (year-1)
for i in range(1, year):  
    if (i%4==0) and (i%100!=0) or (i%400==0):
        total = total + 1
mdays = [0, 31, 28, 31 ,30 ,31 ,30 ,31 ,31 ,30, 31 ,30 ,31] 
if (year%4==0) and (year%100!=0) or (year%400==0): 
    mdays[2] = 29
for i in range(1, month):
    total = total + mdays[i]  
total = total + 1
n = total % 7
print(year, "년 ", month, "월 ")
print("Su Mo Tu We Th Fr Sa")
print("-"*20)
# 1일자의 요일 만큼 빈칸을 출력합니다(0부터 n보다 1작은 수까지 반복실행)
for k in range(0, n, 1):
    print("   ", end="")
# 출력된 빈칸 다음부터 날짜를 출력합니다(7칸이 채워지면 줄바끔을 합니다)
# 1부터 해당월의 끝날짜까지 반복실행
for i in range(1, mdays[month] + 1):
    print("%2d " % i, end="")
    k=k+1
    if (k+1)%7 == 0 : print()

년도 입력:2021
월 입력 : 1
2021 년  1 월
Su Mo Tu We Th Fr Sa
--------------------
                1  2
 3  4  5  6  7  8  9
10 11 12 13 14 15 16
17 18 19 20 21 22 23
24 25 26 27 28 29 30
31

In [21]:
a = 0
while a<10:
    print(a, end=" ")
    a = a + 1

0 1 2 3 4 5 6 7 8 9

In [ ]:
a = 0
while a<k:
    print("   ", end="")
    a = a+1